### ISSUE TITLE
Configuring TCTI with /dev/tpmrm0

### ISSUE THREAD

**Issue by GaelGuegan** [tpm2-software/tpm2-tss#1395]
Hello all,

Because I had a trouble with TCTI : 
```
ERROR:tcti:../tpm2-tss-2.2.0/src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file /dev/tpm0: Device or resource busy`
```
I tried to configure TCTI at compilation when building tpm2-tss with something like :
```shell
./configure --with-tctidefaultconfig=/dev/tpmrm0 --with-tctidefaultmodule=libtss2-tcti-device.so --enable-tcti-mssim=no 
```

However, I have the following error even if the node /dev/tpmrm0 exists.

```shell
engine "tpm2tss" set.
ERROR:tcti:../tpm2-tss-2.2.0/src/tss2-tcti/tcti-device.c:399:Tss2_Tcti_Device_Init() Failed to open device file "/dev/tpmrm0": No such file or directory
WARNING:esys:../tpm2-tss-2.2.0/src/tss2-esys/esys_tcti_default.c:83:tcti_from_init() TCTI init for function 0xb6a7dba8 failed with a000a
WARNING:esys:../tpm2-tss-2.2.0/src/tss2-esys/esys_tcti_default.c:113:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:esys:../tpm2-tss-2.2.0/src/tss2-esys/esys_tcti_default.c:150:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:esys:../tpm2-tss-2.2.0/src/tss2-esys/esys_context.c:68:Esys_Initialize() Initialize default tcti. ErrorCode (0x000a000a)
cannot load Private Key from engine
3069968400:error:8007306F:tpm2-tss-engine:esys_auxctx_init:Some unknown error occured:../tpm2-engine/src/tpm2-tss-engine-common.c:83:
3069968400:error:8007006F:tpm2-tss-engine:tpm2tss_tpm2data_readtpm:Some unknown error occured:../tpm2-engine/src/tpm2-tss-engine-common.c:224:
3069968400:error:8007406F:tpm2-tss-engine:esys_auxctx_free:Some unknown error occured:../tpm2-engine/src/tpm2-tss-engine-common.c:108:
3069968400:error:80064064:tpm2-tss-engine:loadkey:Failed to read TPM2 data:../tpm2-engine/src/tpm2-tss-engine.c:191:
3069968400:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:78:
unable to load Private Key
```

Am I missing something ?

Thanks for your answers

**Comment by diabonas** [comment]
I can reproduce this on my system: the problem is that the configuration string gets quoted twice, so it actually tries to open the device `"/dev/tpmrm0"` (including quotes) instead of `/dev/tpmrm0`. A fix is available in #1397.

BTW, you can also configure the TCTI that tpm2-tss-engine uses by exporting the environment variable `TPM2TSSENGINE_TCTI` with a value of `device:/dev/tpmrm0`. This works even without having the above fix deployed.

**Comment by GaelGuegan** [comment]
In fact, I am using a yocto recipe like this, I tried your solution but I still have the same error : `Failed to open device file "/dev/tpmrm0": No such file or directory`

Here how I am configuring my yocto recipe :
`EXTRA_OECONF += "--with-tctidefaultmodule=libtss2-tcti-device.so --with-tctidefaultconfig="/dev/tpmrm0""`
