### ISSUE TITLE
FAIL: test/integration/fapi-provisioning-with-template

### ISSUE THREAD

**Issue by velopt** [tpm2-software/tpm2-tss#2558]
I met a problem.
I use config like this:
./configure --prefix=/usr --enable-unit --enable-integration
When I run:
make check
There were 2 Fails.

test/integration/fapi-provisioning-with-template.fint and test/integration/fapi-provisioning-with-template-rsa.fint

I use swtpm, and installed it follow the doc from source code. I don't know why, and wander the consequence if I leave it alone.

Log is written below, and the ERROR part is the same.

***
Trying to start simulator swtpm
Starting simulator on port 61018
successfully started daemon: swtpm with PID: 208539
/home/liyan/tpm2-tss-4.0.1
simulator PID: 208539
LISTEN 0      1          127.0.0.1:61018      0.0.0.0:*    users:(("swtpm",pid=208539,fd=3))        
LISTEN 0      1          127.0.0.1:61019      0.0.0.0:*    users:(("swtpm",pid=208539,fd=2))        
Simulator with PID 208539 bound to port 61018 and  61019 successfully.
TPM20TEST_TCTI_NAME=swtpm
TPM20TEST_DEVICE_FILE=
TPM20TEST_SOCKET_ADDRESS=127.0.0.1
TPM20TEST_SOCKET_PORT=61018
TPM20TEST_TCTI=swtpm:host=127.0.0.1,port=61018
WARNING:test:test/helper/tpm_writeekcert.c:93:main() Cert input size is 1284 
WARNING:test:test/helper/tpm_writeekcert.c:96:main() Define NV cert with nv index: 1c00002 
WARNING:test:test/helper/tpm_writeekcert.c:93:main() Cert input size is 1081 
WARNING:test:test/helper/tpm_writeekcert.c:96:main() Define NV cert with nv index: 1c0000a 
Execute the test script
info:test:test/integration/main-fapi.c:413:init_fapi() Using config:
{
     "profile_name": "P_ECC",
     "profile_dir": "./test/data/fapi/",
     "user_dir": "/tmp/fapi_tmpdir.GkOwpO/user/dir",
     "system_dir": "/tmp/fapi_tmpdir.GkOwpO/system_dir",
     "system_pcrs" : [],
     "log_dir" : "/tmp/fapi_tmpdir.GkOwpO",
     "tcti": "swtpm:host=127.0.0.1,port=61018",
     "ek_cert_less": "yes",
} 
WARNING:fapi:src/tss2-fapi/ifapi_io.c:339:ifapi_io_check_create_dir() Directory /tmp/fapi_tmpdir.GkOwpO/user/dir does not exist, creating 
WARNING:fapi:src/tss2-fapi/ifapi_io.c:339:ifapi_io_check_create_dir() Directory /tmp/fapi_tmpdir.GkOwpO/system_dir/policy does not exist, creating 
ERROR:test:test/integration/fapi-provisioning-with-template.int.c:245:test_fapi_provision_template() Provisioning with nonce did not fail. 
info:test:test/integration/main-fapi.c:504:main() Test returned 1 
Script returned 1
TPM changed state during test
State before (/home/liyan/tpm2-tss-4.0.1/test/integration/fapi-provisioning-with-template.fint_state1):
cap0: 0000000500000004000403ffffff000b03ffffff000c03ffffff000d03ffffff00
cap1: 0000000100000018000000000000000100000002000000030000000400000005000000060000000700000008000000090000000a0000000b0000000c0000000d0000000e0000000f000000100000001100000012000000130000001400000015000000160000001700
cap2: 000000010000000000
cap3: 000000010000000000
cap4: 000000010000000000
cap5: 000000010000000000
cap6: 000000010000000201c0000201c0000a00
State after (/home/liyan/tpm2-tss-4.0.1/test/integration/fapi-provisioning-with-template.fint_state2):
cap0: 0000000500000004000403ffffff000b03ffffff000c03ffffff000d03ffffff00
cap1: 0000000100000018000000000000000100000002000000030000000400000005000000060000000700000008000000090000000a0000000b0000000c0000000d0000000e0000000f000000100000001100000012000000130000001400000015000000160000001700
cap2: 000000010000000000
cap3: 000000010000000000
cap4: 000000010000000000
cap5: 00000001000000018100000100
cap6: 000000010000000201c0000201c0000a00
FAIL test/integration/fapi-provisioning-with-template.fint (exit status: 1)

**Comment by JuergenReppSIT** [comment]
The problem is fixed by  #2551

**Comment by PiQuer** [comment]
I can still reproduce this, even though #2551 seems to be merged.

**Comment by velopt** [comment]
> I can still reproduce this, even though #2551 seems to be merged.

+1
But this, seems to be no consequences to what i'm going to do. I just wait and see.

**Comment by JuergenReppSIT** [comment]
Sorry my assumption that the return code handling was responsible for the error was wrong.
The test makes only sense if certificates are stored in nv ram. With the configure option ` --enable-self-generated-certificate` the test should work.
I will add a check that the test will be skipped if no certificate is available in nv ram.
