### ISSUE TITLE
Possible Null-Pointer dereferences 

### ISSUE THREAD

**Issue by PeterHuewe** [tpm2-software/tpm2-tss#435]
Hi,
in the sysapi folder we have quite often the following pattern - e.g.
in sysapi/sysapi/Tss2_Sys_ActivateCredential.c Line 35

```
    if( credentialBlob == 0 )
	{
		SYS_CONTEXT->decryptNull = 1;
	}

MARSHAL_SIMPLE_TPM2B( sysContext, &( credentialBlob->b ) );
---------------------------------------------------------^^^^^^^^^^^^^^^^
```
Doesn't this imply that credentialBlob can be NULL and on the next line we dereference it?
Or am I missing something here?

**Comment by flihp** [comment]
Hi Peter. Looks that way to me. I've fixed something similar in the past. The one I found was a NULL check followed by an immediate dereference so it was a more obvious. I've got coverity scans automated for the tabrmd, I'll be enabling the same here soon-ish. I'm hoping it will help uncover situations like this. Till then bug reports are welcome & patches appreciated!

**Comment by PeterHuewe** [comment]
Unfortunately neither clang nor coverity did find this :/
-- 
Sent from my mobile

**Comment by PeterHuewe** [comment]
Okay I double checked it and actually it's not _real_ a null-pointer dereference (although I still don't like it) - the code works even if credentialBlob is NULL.

What actually happens is,
if you use the address operator on a member of a NULL pointer struct, you get the offset of this member - so it's more or less the offsetof macro.

I tried the same thing within NV_Write:

so 
e.g. something like 
&(((TPM2B_MAX_NV_BUFFER *)NULL)->b)) 
yields 0 as a result, because

#define TPM2B_TYPE1(name, bytes, bufferName)			    \
    typedef union {				    \
	struct  {					    \
	    UINT16  size;				    \
	    BYTE    bufferName[(bytes)];			    \
	} t;						    \
	TPM2B   b;					    \
    } TPM2B_##name

/* Table 79  Definition of TPM2B_MAX_NV_BUFFER Structure */
TPM2B_TYPE1( MAX_NV_BUFFER, MAX_NV_BUFFER_SIZE, buffer );

-> So yes it becomes 0, it's not a NULL pointer dereference, but the code more or less only works since ->b is always the first element (thus offset 0).

If a different element is to be used, then you might get problems.

Also the  &(((TPM2B_MAX_NV_BUFFER *)NULL)->b)) 
is actually undefined behavior according to the standard.

See 
https://stackoverflow.com/questions/26906621/does-struct-name-null-b-cause-undefined-behaviour-in-c11
and of course
https://en.wikipedia.org/wiki/Offsetof 

I'd vote to fix these occurrences - but you can also close this issue - up to you.

**Comment by PeterHuewe** [comment]
How shall we proceed here?

**Comment by flihp** [comment]
It's an interesting observation and one that we can definitely clean up to make the code more clear / less odd. I don't see a reason that we wouldn't take a patch for this.

**Comment by tstruk** [comment]
This should be fixed with the introduction of the MU library. Now this code looks as follows:
```
    if (!credentialBlob) {
        ctx->decryptNull = 1;

        rval = Tss2_MU_UINT16_Marshal(0, ctx->cmdBuffer,
                                      ctx->maxCmdSize,
                                      &ctx->nextData);
    } else {

        rval = Tss2_MU_TPM2B_ID_OBJECT_Marshal(credentialBlob,
                                               ctx->cmdBuffer,
                                               ctx->maxCmdSize,
                                               &ctx->nextData);
    }
```

**Comment by flihp** [comment]
thanks for chasing down these old tickets @tstruk
